#!/bin/bash

if [ -n "${1:-}" ]; then
    day=$1
else
    read -p "day? " day
fi
dir=$(printf "day-%02d" "${day#0}")

mkdir -p "$dir"

for solv in "$dir"/solv-{1,2}.py; do
    [ -f "$solv" ] && continue
    cat > $solv <<PY
#!/usr/bin/env python3

INPUT_FILE_NAME: str = "test-input"
# INPUT_FILE_NAME: str = "input"

with open(INPUT_FILE_NAME, "r") as input_file:
    pass
PY
    chmod +x "$solv"
done


for input in $dir/{,test-}input; do
    if ! [ -f "$input" ] || ( read -p "$input exists, override? [yN] " a && [ "$a" == "y" ] ); then
        touch "$input"
        echo "Content for $input? (press ctrl+d at the end)"
        cat > "$input"
    else
        echo "Not overriding $input"
    fi
done

bash -c "cd $dir; PS1='AOC \\W \$ '; export PS1; bash"
